/**
 * Core Wayland library.
 *
 * <p>Connection management, wire-format marshalling, object/proxy lifecycle, and event dispatch
 * for stubs generated by {@code wayland-scanner}.
 */
package io.github.nhwalker.wayland.core;
